_target_: src.logger.WandBWriter
project_name: "hifigan_dla"
entity: null
run_name: "testing"
mode: "online"
loss_names: ["gen_loss", "disc_loss", "mpd_gen_loss", "msd_gen_loss", "mel_spec_loss", "mpd_feats_gen_loss", "msd_feats_gen_loss", "mpd_disc_loss", "msd_disc_loss"]
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
